"""
Create a program that automatically fills a numeric array with 7
numbers randomly generated by the computer and then show the values
generated on the screen.
"""
import random

arr_n = []

for i in range(0, 7):
    arr_n.append(random.randint(1, 100))

print(arr_n)
