"""
Create a logic that fills an array of 20 positions with numbers
random numbers (between 0 and 99) generated by the computer. Then show the
generated numbers and then put the vector in ascending order, showing at the end
the ordered values.

"""
from random import randint

arr = []

for i in range(20):
    arr.append((randint(0, 99)))

print(arr)
print(sorted(arr))
